---
kind: pipeline
type: kubernetes
name: build-and-publish

steps:
- name: go-build
  image: golang:1.20
  commands:
    - go mod download
    - go install github.com/atomi-ai/atomi/...
  environment:
    GO111MODULE: on
  when:
    event:
      - push

- name: docker-build-and-publish
  image: plugins/docker
  settings:
    repo: adminatomi/server
    tags:
      - "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}"
    dockerfile: Dockerfile
    username: adminatomi
    password:
      from_secret: DOCKER_PASSWORD
    context: .
  when:
    event:
    - push
