// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"firebase.google.com/go/v4"
	"github.com/atomi-ai/atomi/controllers"
	"github.com/atomi-ai/atomi/middlewares"
	"github.com/atomi-ai/atomi/repositories"
	"github.com/atomi-ai/atomi/services"
	"github.com/atomi-ai/atomi/utils"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApplication(db *gorm.DB) (*Application, error) {
	app2 := utils.FirebaseAppProvider()
	userRepository := repositories.NewUserRepository(db)
	authMiddleware := middlewares.NewAuthMiddleware(userRepository, app2)
	addressRepository := repositories.NewAddressRepository(db)
	orderRepository := repositories.NewOrderRepository(db)
	orderItemRepository := repositories.NewOrderItemRepository(db)
	productStoreRepository := repositories.NewProductStoreRepository(db)
	storeRepository := repositories.NewStoreRepository(db)
	userAddressRepository := repositories.NewUserAddressRepository(db)
	userStoreRepository := repositories.NewUserStoreRepository(db)
	addressService := services.NewAddressService(userRepository, addressRepository, userAddressRepository)
	stripeService := services.NewStripeService()
	orderService := services.NewOrderService(orderRepository, orderItemRepository, stripeService)
	userService := services.NewUserService(userRepository)
	addressController := controllers.NewAddressControl(addressService, userService, addressRepository)
	loginController := controllers.NewLoginController(userRepository)
	orderController := controllers.NewOrderController(orderService)
	storeController := controllers.NewStoreController(productStoreRepository, storeRepository, userStoreRepository)
	stripeController := controllers.NewStripeController(userService, stripeService, orderService, addressRepository)
	userController := controllers.NewUserController(userService)
	application := &Application{
		FirebaseApp:            app2,
		AuthMiddleware:         authMiddleware,
		AddressRepository:      addressRepository,
		OrderRepository:        orderRepository,
		OrderItemRepository:    orderItemRepository,
		ProductStoreRepository: productStoreRepository,
		StoreRepository:        storeRepository,
		UserAddressRepository:  userAddressRepository,
		UserRepository:         userRepository,
		UserStoreRepository:    userStoreRepository,
		AddressService:         addressService,
		OrderService:           orderService,
		StripeService:          stripeService,
		UserService:            userService,
		AddressController:      addressController,
		LoginController:        loginController,
		OrderController:        orderController,
		StoreController:        storeController,
		StripeController:       stripeController,
		UserController:         userController,
	}
	return application, nil
}

// wire.go:

type Application struct {
	FirebaseApp    *firebase.App
	AuthMiddleware middlewares.AuthMiddleware

	AddressRepository      repositories.AddressRepository
	OrderRepository        repositories.OrderRepository
	OrderItemRepository    repositories.OrderItemRepository
	ProductStoreRepository repositories.ProductStoreRepository
	StoreRepository        repositories.StoreRepository
	UserAddressRepository  repositories.UserAddressRepository
	UserRepository         repositories.UserRepository
	UserStoreRepository    repositories.UserStoreRepository

	AddressService services.AddressService
	OrderService   services.OrderService
	StripeService  services.StripeService
	UserService    services.UserService

	AddressController controllers.AddressController
	LoginController   controllers.LoginController
	OrderController   controllers.OrderController
	StoreController   controllers.StoreController
	StripeController  controllers.StripeController
	UserController    controllers.UserController
}
