// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/atomi-ai/atomi/controllers"
	"github.com/atomi-ai/atomi/middlewares"
	"github.com/atomi-ai/atomi/repositories"
	"github.com/atomi-ai/atomi/services"
	"github.com/atomi-ai/atomi/utils"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeApplication(db *gorm.DB, authWrapper utils.AuthAppWrapper, blobStorage utils.BlobStorage, stripeWrapper utils.StripeWrapper) (*Application, error) {
	userRepository := repositories.NewUserRepository(db)
	authMiddleware := middlewares.NewAuthMiddleware(userRepository, authWrapper)
	addressRepository := repositories.NewAddressRepository(db)
	userAddressRepository := repositories.NewUserAddressRepository(db)
	addressService := services.NewAddressService(userRepository, addressRepository, userAddressRepository)
	userService := services.NewUserService(userRepository)
	addressController := controllers.NewAddressControl(addressService, userService, addressRepository)
	imageController := controllers.NewImageController(blobStorage)
	loginController := controllers.NewLoginController(userRepository, stripeWrapper)
	managerStoreRepository := repositories.NewManagerStoreRepository(db)
	orderRepository := repositories.NewOrderRepository(db)
	productRepository := repositories.NewProductRepository(db)
	productStoreRepository := repositories.NewProductStoreRepository(db)
	storeRepository := repositories.NewStoreRepository(db)
	productStoreService := services.NewProductStoreService(productRepository, productStoreRepository)
	managerStoreController := controllers.NewManagerStoreController(managerStoreRepository, orderRepository, productRepository, productStoreRepository, storeRepository, productStoreService)
	orderItemRepository := repositories.NewOrderItemRepository(db)
	stripeService := services.NewStripeService()
	uberService := services.NewUberService()
	orderService := services.NewOrderService(orderRepository, orderItemRepository, stripeService, uberService)
	orderController := controllers.NewOrderController(orderService, uberService)
	userStoreRepository := repositories.NewUserStoreRepository(db)
	storeController := controllers.NewStoreController(managerStoreRepository, productStoreRepository, storeRepository, userStoreRepository)
	stripeController := controllers.NewStripeController(userService, stripeService, orderService, uberService, addressRepository)
	deleteUserRequestRepository := repositories.NewDeleteUserRequestRepository(db)
	userController := controllers.NewUserController(userService, deleteUserRequestRepository)
	application := &Application{
		AuthWrapper:                 authWrapper,
		BlobStorage:                 blobStorage,
		StripeWrapper:               stripeWrapper,
		AuthMiddleware:              authMiddleware,
		AddressController:           addressController,
		ImageController:             imageController,
		LoginController:             loginController,
		ManagerStoreController:      managerStoreController,
		OrderController:             orderController,
		StoreController:             storeController,
		StripeController:            stripeController,
		UserController:              userController,
		AddressRepository:           addressRepository,
		DeleteUserRequestRepository: deleteUserRequestRepository,
		ManagerStoreRepository:      managerStoreRepository,
		OrderRepository:             orderRepository,
		OrderItemRepository:         orderItemRepository,
		ProductRepository:           productRepository,
		ProductStoreRepository:      productStoreRepository,
		StoreRepository:             storeRepository,
		UserAddressRepository:       userAddressRepository,
		UserRepository:              userRepository,
		UserStoreRepository:         userStoreRepository,
		AddressService:              addressService,
		OrderService:                orderService,
		ProductStoreService:         productStoreService,
		StripeService:               stripeService,
		UserService:                 userService,
	}
	return application, nil
}

// wire.go:

type Application struct {
	AuthWrapper    utils.AuthAppWrapper
	BlobStorage    utils.BlobStorage
	StripeWrapper  utils.StripeWrapper
	AuthMiddleware middlewares.AuthMiddleware

	AddressController      controllers.AddressController
	ImageController        controllers.ImageController
	LoginController        controllers.LoginController
	ManagerStoreController controllers.ManagerStoreController
	OrderController        controllers.OrderController
	StoreController        controllers.StoreController
	StripeController       controllers.StripeController
	UserController         controllers.UserController

	AddressRepository           repositories.AddressRepository
	DeleteUserRequestRepository repositories.DeleteUserRequestRepository
	ManagerStoreRepository      repositories.ManagerStoreRepository
	OrderRepository             repositories.OrderRepository
	OrderItemRepository         repositories.OrderItemRepository
	ProductRepository           repositories.ProductRepository
	ProductStoreRepository      repositories.ProductStoreRepository
	StoreRepository             repositories.StoreRepository
	UserAddressRepository       repositories.UserAddressRepository
	UserRepository              repositories.UserRepository
	UserStoreRepository         repositories.UserStoreRepository

	AddressService      services.AddressService
	OrderService        services.OrderService
	ProductStoreService services.ProductStoreService
	StripeService       services.StripeService
	UserService         services.UserService
}
